version: '3.5'
services:
  db:
    image: postgres:latest
    container_name: rinha2024q1_db
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: rinha
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"] 
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
      - ./postgres.conf:/docker-entrypoint-initdb.d/postgres.conf
    deploy:
      resources:
        limits:
          cpus: '.6'
          memory: '300MB'

