version: '3.5'
services:
  db:
    image: postgres:latest
    networks:
      - rinha-network-2024q1
    container_name: rinha2024q1_db
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: rinha
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"] 
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./firstload.sql:/docker-entrypoint-initdb.d/firstload.sql
      - ./postgres.conf:/docker-entrypoint-initdb.d/postgres.conf
    deploy:
      resources:
        limits:
          cpus: '.6'
          memory: '300MB'

  api1: &api
    image: rinha2024q1:latest
    restart: always
    networks:
      - rinha-network-2024q1
    container_name: rinha2024q1_1
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "6969"
    deploy:
      resources:
        limits:
          cpus: '.4'
          memory: '100MB'

  api2:
    <<: *api
    container_name: rinha2024q1_2

  nginx:
    image: nginx:latest
    networks:
      - rinha-network-2024q1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '.1'
          memory: '50MB'

networks:
  rinha-network-2024q1:
    driver: bridge
